# fly.toml app configuration file generated for gestion-locative-annemasse on 2026-05-27T21:03:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gestion-locative-annemasse'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '8080'
  SIGNATURE_PATH = 'public/signature.png'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
